services:
  - type: web
    name: ai-legal-api-v2
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      /opt/render/project/.venv/bin/pip install --no-cache-dir -r requirements.txt --verbose
      cd frontend
      npm install --verbose
      npm run build --verbose
      mv build ..
    startCommand: /opt/render/project/.venv/bin/gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: NODE_VERSION
        value: 20.19.2
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        value: Us8vGARh31iSm7UJ409mwl9rMfoZGrBP
