services:
  - type: web
    name: ai-legal-api-v2
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      mv build ..
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: NODE_VERSION
        value: 20.19.2
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        sync: false
